name: Build docker images

on:
  push:
    branches:
      - master
    paths:
      - 'tools/ci/docker/linux/**'
      - '.github/workflows/build_docker.yml'

  pull_request:
    paths:
      - 'tools/ci/docker/linux/**'
      - '.github/workflows/build_docker.yml'

concurrency:
  group: docker-${{github.event.pull_request.number || github.ref}}
  cancel-in-progress: true

env:
  TAG_LINUX: ghcr.io/ouss4/arduino-esp32/esp32-toolchains
  TAG_RPI: ghcr.io/espressif/arduino-esp32/esp32-rpi

jobs:
  docker-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and Load
        uses: docker/build-push-action@v2
        with:
           context: tools/ci/docker/linux
           platforms: linux/amd64
           load: true
           tags: ${{env.TAG_LINUX}}

      - name: Test Image
        run: docker run --rm ${{env.TAG_LINUX}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: tools/ci/docker/linux
          platforms: linux/amd64
          push: true
          tags: ${{env.TAG_LINUX}}

# docker-rpi:
#   runs-on: ubuntu-latest
#   steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v1

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Login to Github Packages
#       uses: docker/login-action@v1
#       with:
#         registry: ghcr.io
#         username: ${{github.actor}}
#         password: ${{secrets.GITHUB_TOKEN}}

#     - name: Build and Load
#       uses: docker/build-push-action@v2
#       with:
#         context: tools/ci/docker/raspberry
#         platforms: linux/arm64
#         load: true
#         tags: ${{env.TAG_RPI}}

#     - name: Test Image
#       run: docker run --rm ${{env.TAG_RPI}}

#     - name: Build and Push
#       uses: docker/build-push-action@v2
#       with:
#         context: tools/ci/docker/raspberry
#         platforms: linux/arm64
#         push: ${{github.ref == 'refs/heads/master'}}
#         tags: ${{env.TAG_RPI}}
