name: Build Examples

on:
  pull_request:
  push:
    branches:
      - master
    tags:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  Linux:
    name: Build ESP32 examples
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker
        uses: docker://docker.io/espressif/idf:release-v4.3
      - name: Build
        uses: arduino/compile-sketches@v1
        with:
          fqbn: 'esp32:esp32:esp32'
          platforms: |
            - name: esp32:esp32
              source-url: https://github.com/espressif/arduino-esp32/releases/download/2.0.2/esp32-2.0.2.zip
          verbose: true
          sketch-paths: |
            - libraries/ESP32/examples/Timer/RepeatTimer

